workflows:
  build-android-apk:
    name: Gerar APK Android
    environment:
      flutter: stable
    scripts:
      - name: Instalar dependencias
        script: flutter pub get
      - name: Construir APK Release
        script: flutter build apk --release --target-platform android-arm,android-arm64
    artifacts:
      - build/**/outputs/**/*.apk
