workflows:
  build-android-apk:
    name: Gerar APK Android
    environment:
      flutter: stable
    scripts:
      - name: Atualizar arquivos do Android para versao moderna
        script: flutter create . --platforms=android --org com.boticario.app --overwrite
      - name: Instalar dependencias
        script: flutter pub get
      - name: Construir APK Release
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
