workflows:
  build-android-apk:
    name: Gerar APK Android
    environment:
      flutter: stable
    scripts:
      - name: Recriar projeto limpo com estrutura moderna
        script: |
          rm -rf android ios web linux macos windows
          flutter create . --platforms=android --org com.boticario.app
      - name: Instalar dependencias
        script: flutter pub get
      - name: Construir APK Release
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
