plugins {
    id "com.android.application"
    id "kotlin-android"
}

android {
    namespace "com.boticario.app"
    compileSdkVersion flutter.compileSdkVersion

    defaultConfig {
        applicationId "com.boticario.app"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
}
